services:
  # bot:
  #   image: ghcr.io/modmail-dev/modmail:master
  #   restart: always
  #   env_file:
  #     - .env
  #   environment:
  #     - CONNECTION_URI=mongodb://mongo
  #   depends_on:
  #     - mongo
  mongo:
    image: mongo:8
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: